import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Nav from "@/components/Nav";
import Footer from "@/components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.svg", // 👈 SVG favicon added
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-primary-50">
        <Nav/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
